/**
 * vn-stock-directory.ts
 * =====================
 * Static lookup table of Vietnamese stock tickers with their
 * exchange (Sàn) and industry group (Nhóm ngành HĐKD).
 *
 * Generated directly from Master FinTop Stock Industry List (191 Tickers).
 */

export interface StockDirectoryEntry {
  symbol: string;
  exchange: 'HOSE' | 'HNX' | 'UPCOM';
  industry: string;
  companyName: string;
}

export const VN_STOCK_DIRECTORY: Record<string, StockDirectoryEntry> = {
  'VEA': { symbol: 'VEA', exchange: 'UPCOM', industry: 'Bán buôn, bán lẻ', companyName: 'Tổng CTCP Máy Động lực và Máy Nông nghiệp Việt Nam' },
  'DST': { symbol: 'DST', exchange: 'HNX', industry: 'Bán buôn, bán lẻ', companyName: 'CTCP Sách và Thiết bị Giáo dục miền Nam' },
  'DGW': { symbol: 'DGW', exchange: 'HOSE', industry: 'Bán buôn, bán lẻ', companyName: 'CTCP Thế Giới Số' },
  'MWG': { symbol: 'MWG', exchange: 'HOSE', industry: 'Bán lẻ', companyName: 'CTCP Đầu tư Thế Giới Di Động' },
  'PNJ': { symbol: 'PNJ', exchange: 'HOSE', industry: 'Bán lẻ', companyName: 'CTCP Vàng bạc Đá quý Phú Nhuận' },
  'FRT': { symbol: 'FRT', exchange: 'HOSE', industry: 'Bán lẻ', companyName: 'CTCP Bán lẻ Kỹ thuật số FPT' },
  'MSN': { symbol: 'MSN', exchange: 'HOSE', industry: 'Bán lẻ', companyName: 'CTCP Tập đoàn Masan' },
  'PLX': { symbol: 'PLX', exchange: 'HOSE', industry: 'Bán lẻ', companyName: 'Tập đoàn Xăng dầu Việt Nam' },
  'PET': { symbol: 'PET', exchange: 'HOSE', industry: 'Bán lẻ', companyName: 'Tổng CTCP Dịch vụ Tổng hợp Dầu khí' },
  'BVH': { symbol: 'BVH', exchange: 'HOSE', industry: 'Bảo hiểm', companyName: 'Tập đoàn Bảo Việt' },
  'BIC': { symbol: 'BIC', exchange: 'HOSE', industry: 'Bảo hiểm', companyName: 'Tổng CTCP Bảo hiểm BIDV' },
  'BMI': { symbol: 'BMI', exchange: 'HOSE', industry: 'Bảo hiểm', companyName: 'Tổng CTCP Bảo Minh' },
  'OGC': { symbol: 'OGC', exchange: 'HOSE', industry: 'Bảo hiểm', companyName: 'CTCP Tập đoàn Đại Dương' },
  'MIG': { symbol: 'MIG', exchange: 'HOSE', industry: 'Bảo hiểm', companyName: 'Tổng CTCP Bảo hiểm Quân đội' },
  'KDH': { symbol: 'KDH', exchange: 'HOSE', industry: 'Bất động sản', companyName: 'CTCP Đầu tư Kinh Doanh Nhà Khang Điền' },
  'HDC': { symbol: 'HDC', exchange: 'HOSE', industry: 'Bất động sản', companyName: 'CTCP Phát triển Nhà Bà Rịa - Vũng Tàu' },
  'HDG': { symbol: 'HDG', exchange: 'HOSE', industry: 'Bất động sản', companyName: 'CTCP Tập đoàn Hà Đô' },
  'DXG': { symbol: 'DXG', exchange: 'HOSE', industry: 'Bất động sản', companyName: 'CTCP Tập đoàn Đất Xanh' },
  'DIG': { symbol: 'DIG', exchange: 'HOSE', industry: 'Bất động sản', companyName: 'Tổng CTCP Đầu tư Phát triển Xây dựng' },
  'HBC': { symbol: 'HBC', exchange: 'HOSE', industry: 'Bất động sản', companyName: 'CTCP Tập đoàn Xây dựng Hòa Bình' },
  'TIG': { symbol: 'TIG', exchange: 'HNX', industry: 'Bất động sản', companyName: 'CTCP Tập đoàn Đầu tư Thăng Long' },
  'NVL': { symbol: 'NVL', exchange: 'HOSE', industry: 'Bất động sản', companyName: 'CTCP Tập đoàn Đầu tư Địa ốc No Va' },
  'CRE': { symbol: 'CRE', exchange: 'HOSE', industry: 'Bất động sản', companyName: 'CTCP Bất động sản Thế Kỷ' },
  'NLG': { symbol: 'NLG', exchange: 'HOSE', industry: 'Bất động sản', companyName: 'CTCP Đầu tư Nam Long' },
  'SCR': { symbol: 'SCR', exchange: 'HOSE', industry: 'Bất động sản', companyName: 'CTCP Địa ốc Sài Gòn Thương Tín' },
  'PDR': { symbol: 'PDR', exchange: 'HOSE', industry: 'Bất động sản', companyName: 'CTCP Phát Đạt' },
  'CEO': { symbol: 'CEO', exchange: 'HNX', industry: 'Bất động sản', companyName: 'CTCP Tập đoàn C.E.O' },
  'VHM': { symbol: 'VHM', exchange: 'HOSE', industry: 'Bất động sản', companyName: 'CTCP Vinhomes' },
  'VRE': { symbol: 'VRE', exchange: 'HOSE', industry: 'Bất động sản', companyName: 'CTCP Vincom Retail' },
  'VIC': { symbol: 'VIC', exchange: 'HOSE', industry: 'Bất động sản', companyName: 'Tập đoàn Vingroup' },
  'HQC': { symbol: 'HQC', exchange: 'HOSE', industry: 'Bất động sản', companyName: 'CTCP Tư vấn Thương mại Dịch vụ Địa ốc Hoàng Quân' },
  'AAV': { symbol: 'AAV', exchange: 'HNX', industry: 'Bất động sản', companyName: 'CTCP Đầu tư AAV Group' },
  'API': { symbol: 'API', exchange: 'HNX', industry: 'Bất động sản', companyName: 'CTCP Đầu tư Châu Á - Thái Bình Dương' },
  'NDN': { symbol: 'NDN', exchange: 'HNX', industry: 'Bất động sản', companyName: 'CTCP Đầu tư Phát triển Nhà Đà Nẵng' },
  'TCH': { symbol: 'TCH', exchange: 'HOSE', industry: 'Bất động sản', companyName: 'CTCP Đầu tư Dịch vụ Tài chính Hoàng Huy' },
  'NTL': { symbol: 'NTL', exchange: 'HOSE', industry: 'Bất động sản', companyName: 'CTCP Phát triển Đô thị Từ Liêm' },
  'PHR': { symbol: 'PHR', exchange: 'HOSE', industry: 'BĐS - KCN', companyName: 'CTCP Cao su Phước Hòa' },
  'TIP': { symbol: 'TIP', exchange: 'HOSE', industry: 'BĐS - KCN', companyName: 'CTCP Phát triển Khu công nghiệp Tín Nghĩa' },
  'D2D': { symbol: 'D2D', exchange: 'HOSE', industry: 'BĐS - KCN', companyName: 'CTCP Phát triển Đô thị Industrial Zone D2D' },
  'SZC': { symbol: 'SZC', exchange: 'HOSE', industry: 'BĐS - KCN', companyName: 'CTCP Sonadezi Châu Đức' },
  'GVR': { symbol: 'GVR', exchange: 'HOSE', industry: 'BĐS - KCN', companyName: 'Tập đoàn Công nghiệp Cao su Việt Nam' },
  'KBC': { symbol: 'KBC', exchange: 'HOSE', industry: 'BĐS - KCN', companyName: 'Tổng CTCP Phát triển Đô thị Kinh Bắc' },
  'BCM': { symbol: 'BCM', exchange: 'HOSE', industry: 'BĐS - KCN', companyName: 'Tổng CTCP Đầu tư và Phát triển Công nghiệp' },
  'LHG': { symbol: 'LHG', exchange: 'HOSE', industry: 'BĐS - KCN', companyName: 'CTCP Long Hậu' },
  'IDC': { symbol: 'IDC', exchange: 'HOSE', industry: 'BĐS - KCN', companyName: 'Tổng CTCP IDICO' },
  'VGC': { symbol: 'VGC', exchange: 'HOSE', industry: 'BĐS - KCN', companyName: 'Tổng CTCP Viglacera' },
  'SHS': { symbol: 'SHS', exchange: 'HNX', industry: 'Chứng khoán', companyName: 'CTCP Chứng khoán Sài Gòn - Hà Nội' },
  'HCM': { symbol: 'HCM', exchange: 'HOSE', industry: 'Chứng khoán', companyName: 'CTCP Chứng khoán TP.HCM' },
  'VCK': { symbol: 'VCK', exchange: 'HOSE', industry: 'Chứng khoán', companyName: 'CTCP Chứng khoán Vincom' },
  'VND': { symbol: 'VND', exchange: 'HOSE', industry: 'Chứng khoán', companyName: 'CTCP Chứng khoán VNDIRECT' },
  'SSI': { symbol: 'SSI', exchange: 'HOSE', industry: 'Chứng khoán', companyName: 'CTCP Chứng khoán SSI' },
  'TCX': { symbol: 'TCX', exchange: 'HOSE', industry: 'Chứng khoán', companyName: 'CTCP Chứng khoán TCBS' },
  'FTS': { symbol: 'FTS', exchange: 'HOSE', industry: 'Chứng khoán', companyName: 'CTCP Chứng khoán FPT' },
  'AGR': { symbol: 'AGR', exchange: 'HOSE', industry: 'Chứng khoán', companyName: 'CTCP Chứng khoán Agribank' },
  'APG': { symbol: 'APG', exchange: 'HOSE', industry: 'Chứng khoán', companyName: 'CTCP Chứng khoán APG' },
  'VCI': { symbol: 'VCI', exchange: 'HOSE', industry: 'Chứng khoán', companyName: 'CTCP Chứng khoán Bản Việt' },
  'BVS': { symbol: 'BVS', exchange: 'HNX', industry: 'Chứng khoán', companyName: 'CTCP Chứng khoán Bảo Việt' },
  'BSI': { symbol: 'BSI', exchange: 'HOSE', industry: 'Chứng khoán', companyName: 'CTCP Chứng khoán BIDV' },
  'CTS': { symbol: 'CTS', exchange: 'HOSE', industry: 'Chứng khoán', companyName: 'CTCP Chứng khoán Ngân hàng Công thương' },
  'AAS': { symbol: 'AAS', exchange: 'UPCOM', industry: 'Chứng khoán', companyName: 'CTCP Chứng khoán SmartInvest' },
  'MBS': { symbol: 'MBS', exchange: 'HOSE', industry: 'Chứng khoán', companyName: 'CTCP Chứng khoán MB' },
  'ORS': { symbol: 'ORS', exchange: 'HOSE', industry: 'Chứng khoán', companyName: 'CTCP Chứng khoán Tiên Phong' },
  'TCI': { symbol: 'TCI', exchange: 'UPCOM', industry: 'Chứng khoán', companyName: 'CTCP Chứng khoán Thành Công' },
  'VIX': { symbol: 'VIX', exchange: 'HOSE', industry: 'Chứng khoán', companyName: 'CTCP Chứng khoán VIX' },
  'SBS': { symbol: 'SBS', exchange: 'UPCOM', industry: 'Chứng khoán', companyName: 'CTCP Chứng khoán SBS' },
  'VIG': { symbol: 'VIG', exchange: 'HNX', industry: 'Chứng khoán', companyName: 'CTCP Chứng khoán Thương mại và Công nghiệp Việt Nam' },
  'FPT': { symbol: 'FPT', exchange: 'HOSE', industry: 'Công nghệ thông tin', companyName: 'CTCP FPT' },
  'CMG': { symbol: 'CMG', exchange: 'HOSE', industry: 'Công nghệ thông tin', companyName: 'CTCP Tập đoàn Công nghệ CMC' },
  'GAS': { symbol: 'GAS', exchange: 'HOSE', industry: 'Dầu khí', companyName: 'Tổng CTCP Khí Việt Nam' },
  'BSR': { symbol: 'BSR', exchange: 'HOSE', industry: 'Dầu khí', companyName: 'CTCP Lọc Hóa dầu Bình Sơn' },
  'PVS': { symbol: 'PVS', exchange: 'HNX', industry: 'Dầu khí', companyName: 'Tổng CTCP Dịch vụ Kỹ thuật Dầu khí Việt Nam' },
  'PVD': { symbol: 'PVD', exchange: 'HOSE', industry: 'Dầu khí', companyName: 'Tổng CTCP Khoan và Dịch vụ Khoan Dầu khí' },
  'PVB': { symbol: 'PVB', exchange: 'HNX', industry: 'Dầu khí', companyName: 'CTCP Bọc ống Dầu khí Việt Nam' },
  'PVC': { symbol: 'PVC', exchange: 'HNX', industry: 'Dầu khí', companyName: 'Tổng CTCP Xây lắp Dầu khí Việt Nam' },
  'OIL': { symbol: 'OIL', exchange: 'UPCOM', industry: 'Dầu khí', companyName: 'Tổng CTCP Dầu Việt Nam' },
  'PLC': { symbol: 'PLC', exchange: 'HNX', industry: 'Dầu khí', companyName: 'CTCP Hóa dầu Petrolimex' },
  'TNG': { symbol: 'TNG', exchange: 'HNX', industry: 'Dệt may', companyName: 'CTCP Đầu tư và Thương mại TNG' },
  'TCM': { symbol: 'TCM', exchange: 'HOSE', industry: 'Dệt may', companyName: 'CTCP Dệt may - Đầu tư - Thương mại Thành Công' },
  'MSH': { symbol: 'MSH', exchange: 'HOSE', industry: 'Dệt may', companyName: 'CTCP May Sông Hồng' },
  'VGT': { symbol: 'VGT', exchange: 'UPCOM', industry: 'Dệt may', companyName: 'Tập đoàn Dệt May Việt Nam' },
  'STK': { symbol: 'STK', exchange: 'HOSE', industry: 'Dệt may', companyName: 'CTCP Sợi Thế Kỷ' },
  'DVN': { symbol: 'DVN', exchange: 'UPCOM', industry: 'Dược phẩm - Y tế', companyName: 'Tổng CTCP Dược Việt Nam' },
  'DHG': { symbol: 'DHG', exchange: 'HOSE', industry: 'Dược phẩm - Y tế', companyName: 'CTCP Dược Hậu Giang' },
  'MBG': { symbol: 'MBG', exchange: 'HNX', industry: 'Đa ngành', companyName: 'CTCP Tập đoàn MBG' },
  'HAG': { symbol: 'HAG', exchange: 'HOSE', industry: 'Đa ngành', companyName: 'CTCP Hoàng Anh Gia Lai' },
  'HHS': { symbol: 'HHS', exchange: 'HOSE', industry: 'Đa ngành', companyName: 'CTCP Đầu tư Dịch vụ Hoàng Huy' },
  'HVN': { symbol: 'HVN', exchange: 'HOSE', industry: 'Hàng không', companyName: 'Tổng CTCP Hàng không Việt Nam' },
  'ACV': { symbol: 'ACV', exchange: 'UPCOM', industry: 'Hàng không', companyName: 'Tổng CTCP Cảng hàng không Việt Nam' },
  'VJX': { symbol: 'VJX', exchange: 'HOSE', industry: 'Hàng không', companyName: 'CTCP Hàng không Vietjet' },
  'MSR': { symbol: 'MSR', exchange: 'UPCOM', industry: 'Khai khoáng', companyName: 'CTCP Tài nguyên Masan' },
  'POW': { symbol: 'POW', exchange: 'HOSE', industry: 'Năng lượng/Điện/Nước', companyName: 'Tổng CTCP Điện lực Dầu khí Việt Nam' },
  'REE': { symbol: 'REE', exchange: 'HOSE', industry: 'Năng lượng/Điện/Nước', companyName: 'CTCP Cơ Điện Lạnh' },
  'NT2': { symbol: 'NT2', exchange: 'HOSE', industry: 'Năng lượng/Điện/Nước', companyName: 'CTCP Điện lực Dầu khí Nhơn Trạch 2' },
  'BWE': { symbol: 'BWE', exchange: 'HOSE', industry: 'Năng lượng/Điện/Nước', companyName: 'CTCP Nước - Môi trường Bình Dương' },
  'PPC': { symbol: 'PPC', exchange: 'HOSE', industry: 'Năng lượng/Điện/Nước', companyName: 'CTCP Nhiệt điện Phả Lại' },
  'GEG': { symbol: 'GEG', exchange: 'HOSE', industry: 'Năng lượng/Điện/Nước', companyName: 'CTCP Điện Gia Lai' },
  'QTP': { symbol: 'QTP', exchange: 'UPCOM', industry: 'Năng lượng/Điện/Nước', companyName: 'CTCP Nhiệt điện Quảng Ninh' },
  'VCB': { symbol: 'VCB', exchange: 'HOSE', industry: 'Ngân Hàng', companyName: 'Ngân hàng TMCP Ngoại Thương Việt Nam' },
  'ACB': { symbol: 'ACB', exchange: 'HOSE', industry: 'Ngân Hàng', companyName: 'Ngân hàng TMCP Á Châu' },
  'TCB': { symbol: 'TCB', exchange: 'HOSE', industry: 'Ngân Hàng', companyName: 'Ngân hàng TMCP Kỹ Thương Việt Nam' },
  'MBB': { symbol: 'MBB', exchange: 'HOSE', industry: 'Ngân Hàng', companyName: 'Ngân hàng TMCP Quân Đội' },
  'CTG': { symbol: 'CTG', exchange: 'HOSE', industry: 'Ngân Hàng', companyName: 'Ngân hàng TMCP Công Thương Việt Nam' },
  'BID': { symbol: 'BID', exchange: 'HOSE', industry: 'Ngân Hàng', companyName: 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam' },
  'HDB': { symbol: 'HDB', exchange: 'HOSE', industry: 'Ngân Hàng', companyName: 'Ngân hàng TMCP Phát triển TP.HCM' },
  'VIB': { symbol: 'VIB', exchange: 'HOSE', industry: 'Ngân Hàng', companyName: 'Ngân hàng TMCP Quốc Tế' },
  'VPB': { symbol: 'VPB', exchange: 'HOSE', industry: 'Ngân Hàng', companyName: 'Ngân hàng TMCP Việt Nam Thịnh Vượng' },
  'SHB': { symbol: 'SHB', exchange: 'HOSE', industry: 'Ngân Hàng', companyName: 'Ngân hàng TMCP Sài Gòn - Hà Nội' },
  'STB': { symbol: 'STB', exchange: 'HOSE', industry: 'Ngân Hàng', companyName: 'Ngân hàng TMCP Sài Gòn Thương Tín' },
  'NVB': { symbol: 'NVB', exchange: 'HNX', industry: 'Ngân Hàng', companyName: 'Ngân hàng TMCP Quốc Dân' },
  'TPB': { symbol: 'TPB', exchange: 'HOSE', industry: 'Ngân Hàng', companyName: 'Ngân hàng TMCP Tiên Phong' },
  'EIB': { symbol: 'EIB', exchange: 'HOSE', industry: 'Ngân Hàng', companyName: 'Ngân hàng TMCP Xuất Nhập Khẩu' },
  'BVB': { symbol: 'BVB', exchange: 'UPCOM', industry: 'Ngân Hàng', companyName: 'Ngân hàng TMCP Bản Việt' },
  'OCB': { symbol: 'OCB', exchange: 'HOSE', industry: 'Ngân Hàng', companyName: 'Ngân hàng TMCP Phương Đông' },
  'LPB': { symbol: 'LPB', exchange: 'HOSE', industry: 'Ngân Hàng', companyName: 'Ngân hàng TMCP Bưu Điện Liên Việt' },
  'MSB': { symbol: 'MSB', exchange: 'HOSE', industry: 'Ngân Hàng', companyName: 'Ngân hàng TMCP Hàng Hải' },
  'DCM': { symbol: 'DCM', exchange: 'HOSE', industry: 'Phân bón', companyName: 'CTCP Phân bón Dầu khí Cà Mau' },
  'DPM': { symbol: 'DPM', exchange: 'HOSE', industry: 'Phân bón', companyName: 'Tổng CTCP Phân bón và Hóa chất Dầu khí' },
  'BFC': { symbol: 'BFC', exchange: 'HOSE', industry: 'Phân bón', companyName: 'CTCP Phân bón Bình Điền' },
  'DRC': { symbol: 'DRC', exchange: 'HOSE', industry: 'Sản xuất NN/CN', companyName: 'CTCP Cao su Đà Nẵng' },
  'FIT': { symbol: 'FIT', exchange: 'HOSE', industry: 'Sản xuất NN/CN', companyName: 'CTCP Tập đoàn F.I.T' },
  'GIL': { symbol: 'GIL', exchange: 'HOSE', industry: 'Sản xuất NN/CN', companyName: 'CTCP Sản xuất Kinh doanh Xuất nhập khẩu Bình Thạnh' },
  'HII': { symbol: 'HII', exchange: 'HOSE', industry: 'Sản xuất NN/CN', companyName: 'CTCP An Tiến Phong' },
  'HNG': { symbol: 'HNG', exchange: 'HOSE', industry: 'Sản xuất NN/CN', companyName: 'CTCP Nông nghiệp Quốc tế Hoàng Anh Gia Lai' },
  'ABS': { symbol: 'ABS', exchange: 'HOSE', industry: 'Sản xuất NN/CN', companyName: 'CTCP Dịch vụ Nông nghiệp Bình Thuận' },
  'GEX': { symbol: 'GEX', exchange: 'HOSE', industry: 'Sản xuất NN/CN', companyName: 'CTCP Tập đoàn GELEX' },
  'DHC': { symbol: 'DHC', exchange: 'HOSE', industry: 'Sản xuất NN/CN', companyName: 'CTCP Đông Hải Bến Tre' },
  'DGC': { symbol: 'DGC', exchange: 'HOSE', industry: 'Sản xuất NN/CN', companyName: 'CTCP Tập đoàn Hóa chất Đức Giang' },
  'PLP': { symbol: 'PLP', exchange: 'HOSE', industry: 'Sản xuất NN/CN', companyName: 'CTCP Sản xuất và Công nghệ Nhựa Tập đoàn' },
  'VPG': { symbol: 'VPG', exchange: 'HOSE', industry: 'Sản xuất NN/CN', companyName: 'CTCP Thương mại Đầu tư Việt Phát' },
  'TTF': { symbol: 'TTF', exchange: 'HOSE', industry: 'Sản xuất NN/CN', companyName: 'CTCP Tập đoàn Kỹ nghệ Gỗ Trường Thành' },
  'DRI': { symbol: 'DRI', exchange: 'UPCOM', industry: 'Sản xuất NN/CN', companyName: 'CTCP Đầu tư Cao su Đắk Lắk' },
  'CSV': { symbol: 'CSV', exchange: 'HOSE', industry: 'Sản xuất NN/CN', companyName: 'CTCP Hóa chất Cơ bản Miền Nam' },
  'LAS': { symbol: 'LAS', exchange: 'HNX', industry: 'Sản xuất NN/CN', companyName: 'CTCP Supe Phốt phát và Hóa chất Lâm Thao' },
  'DDV': { symbol: 'DDV', exchange: 'UPCOM', industry: 'Sản xuất NN/CN', companyName: 'CTCP DAP - VINACHEM' },
  'HPG': { symbol: 'HPG', exchange: 'HOSE', industry: 'Thép - Vật liệu', companyName: 'CTCP Tập đoàn Hòa Phát' },
  'HSG': { symbol: 'HSG', exchange: 'HOSE', industry: 'Thép - Vật liệu', companyName: 'CTCP Tập đoàn Hoa Sen' },
  'NKG': { symbol: 'NKG', exchange: 'HOSE', industry: 'Thép - Vật liệu', companyName: 'CTCP Thép Nam Kim' },
  'SMC': { symbol: 'SMC', exchange: 'HOSE', industry: 'Thép - Vật liệu', companyName: 'CTCP Đầu tư Thương mại SMC' },
  'TLH': { symbol: 'TLH', exchange: 'HOSE', industry: 'Thép - Vật liệu', companyName: 'CTCP Tập đoàn Thép Tiến Lên' },
  'TVN': { symbol: 'TVN', exchange: 'UPCOM', industry: 'Thép - Vật liệu', companyName: 'Tổng CTCP Thép Việt Nam' },
  'VGS': { symbol: 'VGS', exchange: 'HNX', industry: 'Thép - Vật liệu', companyName: 'CTCP Ống thép Việt Đức VG PIPE' },
  'BMP': { symbol: 'BMP', exchange: 'HOSE', industry: 'Thép - Vật liệu', companyName: 'CTCP Nhựa Bình Minh' },
  'VCS': { symbol: 'VCS', exchange: 'HNX', industry: 'Thép - Vật liệu', companyName: 'CTCP Vicostone' },
  'AAA': { symbol: 'AAA', exchange: 'HOSE', industry: 'Thép - Vật liệu', companyName: 'CTCP Nhựa An Phát Xanh' },
  'HT1': { symbol: 'HT1', exchange: 'HOSE', industry: 'Thép - Vật liệu', companyName: 'CTCP Xi măng Hà Tiên 1' },
  'BCC': { symbol: 'BCC', exchange: 'HNX', industry: 'Thép - Vật liệu', companyName: 'CTCP Xi măng Bỉm Sơn' },
  'VNM': { symbol: 'VNM', exchange: 'HOSE', industry: 'Thực phẩm', companyName: 'CTCP Sữa Việt Nam' },
  'DBC': { symbol: 'DBC', exchange: 'HOSE', industry: 'Thực phẩm', companyName: 'CTCP Tập đoàn Dabaco Việt Nam' },
  'SAB': { symbol: 'SAB', exchange: 'HOSE', industry: 'Thực phẩm', companyName: 'Tổng CTCP Bia - Rượu - Nước giải khát Sài Gòn' },
  'KDC': { symbol: 'KDC', exchange: 'HOSE', industry: 'Thực phẩm', companyName: 'CTCP Tập đoàn KIDO' },
  'SBT': { symbol: 'SBT', exchange: 'HOSE', industry: 'Thực phẩm', companyName: 'CTCP Thành Thành Công - Biên Hòa' },
  'LSS': { symbol: 'LSS', exchange: 'HOSE', industry: 'Thực phẩm', companyName: 'CTCP Mía đường Lam Sơn' },
  'NAF': { symbol: 'NAF', exchange: 'HOSE', industry: 'Thực phẩm', companyName: 'CTCP Nafoods Group' },
  'BAF': { symbol: 'BAF', exchange: 'HOSE', industry: 'Thực phẩm', companyName: 'CTCP Nông nghiệp BAF Việt Nam' },
  'VHC': { symbol: 'VHC', exchange: 'HOSE', industry: 'Thủy sản', companyName: 'CTCP Vĩnh Hoàn' },
  'MPC': { symbol: 'MPC', exchange: 'UPCOM', industry: 'Thủy sản', companyName: 'CTCP Tập đoàn Thủy sản Minh Phú' },
  'FMC': { symbol: 'FMC', exchange: 'HOSE', industry: 'Thủy sản', companyName: 'CTCP Thực phẩm Sao Ta' },
  'CMX': { symbol: 'CMX', exchange: 'HOSE', industry: 'Thủy sản', companyName: 'CTCP Camimex Group' },
  'ANV': { symbol: 'ANV', exchange: 'HOSE', industry: 'Thủy sản', companyName: 'CTCP Nam Việt' },
  'ASM': { symbol: 'ASM', exchange: 'HOSE', industry: 'Thủy sản', companyName: 'CTCP Tập đoàn Sao Mai' },
  'IDI': { symbol: 'IDI', exchange: 'HOSE', industry: 'Thủy sản', companyName: 'CTCP Đầu tư và Phát triển Đa Quốc Gia I.D.I' },
  'HAH': { symbol: 'HAH', exchange: 'HOSE', industry: 'Vận tải biển', companyName: 'CTCP Vận tải và Xếp dỡ Hải An' },
  'PVT': { symbol: 'PVT', exchange: 'HOSE', industry: 'Vận tải biển', companyName: 'Tổng CTCP Vận tải Dầu khí' },
  'GMD': { symbol: 'GMD', exchange: 'HOSE', industry: 'Vận tải biển', companyName: 'CTCP Gemadept' },
  'MHC': { symbol: 'MHC', exchange: 'HOSE', industry: 'Vận tải biển', companyName: 'CTCP MHC' },
  'VSC': { symbol: 'VSC', exchange: 'HOSE', industry: 'Vận tải biển', companyName: 'CTCP Container Việt Nam' },
  'VOS': { symbol: 'VOS', exchange: 'HOSE', industry: 'Vận tải biển', companyName: 'CTCP Vận tải Biển Việt Nam' },
  'SKG': { symbol: 'SKG', exchange: 'HOSE', industry: 'Vận tải biển', companyName: 'CTCP Tàu cao tốc Superdong - Kiên Giang' },
  'PVP': { symbol: 'PVP', exchange: 'UPCOM', industry: 'Vận tải biển', companyName: 'CTCP Vận tải Dầu khí Thái Bình Dương' },
  'DL1': { symbol: 'DL1', exchange: 'HNX', industry: 'Vận tải kho', companyName: 'CTCP Tập đoàn Alpha Seven' },
  'DXP': { symbol: 'DXP', exchange: 'HNX', industry: 'Vận tải kho', companyName: 'CTCP Cảng Đoạn Xá' },
  'VIP': { symbol: 'VIP', exchange: 'HOSE', industry: 'Vận tải kho', companyName: 'CTCP Vận tải Xăng dầu VIP' },
  'SGP': { symbol: 'SGP', exchange: 'UPCOM', industry: 'Vận tải kho', companyName: 'CTCP Cảng Sài Gòn' },
  'VTP': { symbol: 'VTP', exchange: 'HOSE', industry: 'Vận tải kho', companyName: 'Tổng CTCP Bưu chính Viettel' },
  'VGI': { symbol: 'VGI', exchange: 'UPCOM', industry: 'Viễn thông', companyName: 'Tổng CTCP Đầu tư Quốc tế Viettel' },
  'CII': { symbol: 'CII', exchange: 'HOSE', industry: 'Xây dựng', companyName: 'CTCP Đầu tư Hạ tầng Kỹ thuật TP.HCM' },
  'CTD': { symbol: 'CTD', exchange: 'HOSE', industry: 'Xây dựng', companyName: 'CTCP Xây dựng Coteccons' },
  'CTR': { symbol: 'CTR', exchange: 'HOSE', industry: 'Xây dựng', companyName: 'CTCP Công trình Viettel' },
  'FCN': { symbol: 'FCN', exchange: 'HOSE', industry: 'Xây dựng', companyName: 'CTCP FECON' },
  'HHV': { symbol: 'HHV', exchange: 'HOSE', industry: 'Xây dựng', companyName: 'CTCP Đầu tư Hạ tầng Giao thông Đèo Cả' },
  'KSB': { symbol: 'KSB', exchange: 'HOSE', industry: 'Xây dựng', companyName: 'CTCP Khoáng sản và Xây dựng Bình Dương' },
  'PC1': { symbol: 'PC1', exchange: 'HOSE', industry: 'Xây dựng', companyName: 'CTCP Xây lắp Điện 1' },
  'DTD': { symbol: 'DTD', exchange: 'HNX', industry: 'Xây dựng', companyName: 'CTCP Đầu tư Phát triển Thành Đạt' },
  'IDJ': { symbol: 'IDJ', exchange: 'HNX', industry: 'Xây dựng', companyName: 'CTCP Đầu tư Quốc tế Việt Nam' },
  'S99': { symbol: 'S99', exchange: 'HNX', industry: 'Xây dựng', companyName: 'CTCP SCI' },
  'G36': { symbol: 'G36', exchange: 'UPCOM', industry: 'Xây dựng', companyName: 'Tổng CTCP 36' },
  'LCG': { symbol: 'LCG', exchange: 'HOSE', industry: 'Xây dựng', companyName: 'CTCP LIZEN' },
  'HTN': { symbol: 'HTN', exchange: 'HOSE', industry: 'Xây dựng', companyName: 'CTCP Hưng Thịnh Incons' },
  'MST': { symbol: 'MST', exchange: 'HNX', industry: 'Xây dựng', companyName: 'CTCP Đầu tư MST' },
  'EVG': { symbol: 'EVG', exchange: 'HOSE', industry: 'Xây dựng', companyName: 'CTCP Tập đoàn Everland' },
  'VCG': { symbol: 'VCG', exchange: 'HOSE', industry: 'Xây dựng', companyName: 'Tổng CTCP Xuất Nhập khẩu và Xây dựng Việt Nam' },
};
